"""initial PostgreSQL schema

Revision ID: 1540acf841a5
Revises: 
Create Date: 2026-08-28 14:45:40.105577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1540acf841a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    try:
        op.create_table('lookup_history',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('ip', sa.String(), nullable=False),
            sa.Column('city', sa.String(), nullable=True),
            sa.Column('region', sa.String(), nullable=True),
            sa.Column('country', sa.String(), nullable=True),
            sa.Column('latitude', sa.Float(), nullable=True),
            sa.Column('longitude', sa.Float(), nullable=True),
            sa.Column('provider', sa.String(), nullable=True),
            sa.Column('timestamp', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_ip_timestamp', 'lookup_history', ['ip', 'timestamp'], unique=False)
        op.create_index(op.f('ix_lookup_history_ip'), 'lookup_history', ['ip'], unique=False)
        op.create_index(op.f('ix_lookup_history_timestamp'), 'lookup_history', ['timestamp'], unique=False)
    except Exception:
        # Table likely already exists
        pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lookup_history_timestamp'), table_name='lookup_history')
    op.drop_index(op.f('ix_lookup_history_ip'), table_name='lookup_history')
    op.drop_index('idx_ip_timestamp', table_name='lookup_history')
    op.alter_column('lookup_history', 'ip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
